// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.rejna.abet.workflow.persistence;

import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Lock_Roo_Configurable {
    
    declare @type: Lock: @Configurable;
    
}
